### ISSUE TITLE
the example in horovod/tensorflow-mnist.yaml maybe add worker command to run succesfully

### ISSUE THREAD

**Issue by malixian** [kubeflow/mpi-operator#240]
original yaml is

> Worker:

      replicas: 2
      template:
        spec:
          containers:
          - command:
            - ""
            image: horovod-cpu:latest
            name: mpi-worker
when we create this yaml we will find `“No command specified”` Error while creating pod in worker pod.
change yaml to this is ok

> Worker:

      replicas: 2
      template:
        spec:
          containers:
          - command:
            - "sleep"
            args:
            - "infinity"
            image: horovod-cpu:latest
            name: mpi-worker

but this problem is args equal` "infinity" `means this pod may never be compeleted.so what is the best way to solve this problem?

**Comment by terrytangyuan** [comment]
Currently we only check whether `command` is specified, if not, we will assign default command: https://github.com/kubeflow/mpi-operator/blob/master/pkg/controllers/v1/mpi_job_controller.go#L1114-L1117

In your case, your command is specified as `""` so the error is expected.

Could you remove `command` and `args` following the examples in the repo and try again? You do not need to specify command for worker since worker will use the command that's specified in launcher.

**Comment by malixian** [comment]
Thanks, i will try it again.
